### ISSUE TITLE
Does EndoDAC Require Retraining for Different Endoscope Cameras?

### ISSUE THREAD

**Issue by Rasoul-Sharifian** [BeileiCui/EndoDAC#10]
Thank you for sharing the repository.

It is quite useful that EndoDAC is designed in a way that allows it to be compatible with any endoscope. As I understand it, this capability stems from its ability to estimate camera intrinsics during the training phase.

My question is:
Does this mean that to perform inference on images captured by a different endoscope, EndoDAC requires retraining with the new camera's parameters?

Thank you!

**Comment by BeileiCui** [comment]
The constraint that enables the network to estimate K is based on a constraint between the target frame and the reprojected frame from source to target. Therefore if the scene is quite different from the training one, the estimation of K might not be accurate. 

I have not tried it on another dataset, maybe you could have a try first if the estimation is good with the checkpoint I presented. But I would say it should be better to retrain if you want an accurate K estimation.

**Comment by Rasoul-Sharifian** [comment]
Thank you for your response.

I have a follow-up question regarding the generalization of the depth estimation module in EndoDAC. 

Is your previous comment also true for the depth estimation module itself, not the K estimation head?
I mean once the EndoDAC is trained, is the depth module capable of estimating depth for another camera?
For example in your paper, you have reported the results on the Hamlyn dataset, but without finetuning to re-estimate the corresponding K. This appears to demonstrate the model's generalization capability, but is this approach generally valid?

Thank you!

**Comment by BeileiCui** [comment]
@Rasoul-Sharifian Hi, although the depth estimation relies on the reprojection too, it has much more generalization ability than K estimation. But there are cases where the estimation might not be accurate, for example, SCARED does not include any colon images so if you directly test the checkpoint on C3VD or SimCol3D (colon datasets), the performance may drop.

Anyway, this is a fine-tuning, or called adaptation method, it is designed to be adaptable to various datasets because only surgical videos are required to be trained, so if you want a good performance you better fine-tune it on your datasets.
