### ISSUE TITLE
CUDA_VISIBLE_DEVICES=0 python train_end_to_end.py --data_path <your_data_path> --log_dir './logs'

### ISSUE THREAD

**Issue by wwj-53** [BeileiCui/EndoDAC#6]
please help me.

(endodac) wwj@cpnt:~/3DGS/EndoDAC$ CUDA_VISIBLE_DEVICES=0 python train_end_to_end.py --data_path /home/wwj/3DGS/EndoDAC/datasets/endovis --log_dir './logs'
/home/wwj/3DGS/EndoDAC/models/backbones/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/wwj/3DGS/EndoDAC/models/backbones/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/wwj/3DGS/EndoDAC/models/backbones/layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
load pretrained weight from /home/wwj/3DGS/EndoDAC/pretrained_model/depth_anything_vitb14.pth

Training model named:
   endodac
Models and tensorboard events files are saved to:
   ./logs
Training is using:
   cuda
/home/wwj/anaconda3/envs/endodac/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1678402374358/work/aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/wwj/3DGS/EndoDAC/train_end_to_end.py", line 25, in <module>
    trainer = Trainer(opts)
  File "/home/wwj/3DGS/EndoDAC/trainer_end_to_end.py", line 203, in __init__
    self.gt_depths = np.load(gt_path, fix_imports=True, encoding='latin1')["data"]
  File "/home/wwj/anaconda3/envs/endodac/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/wwj/3DGS/EndoDAC/splits/endovis/gt_depths.npz'

**Comment by BeileiCui** [comment]
Hi @wwj-53 , based on your errors, I think the problem is you did not generate the ground truth depth file (which is `gt_depths.npz`), which we used to validate during training.

If you are trying to fine-tune on SCARED. Then I suggest first to prepare the dataset follow [Af-SfMLearner](https://github.com/ShuweiShao/AF-SfMLearner). You need to prepare the dataset and generate the `gt_depths.npz` accordingly.

If you are fine-tuning on some other dataset or you just don't want to validate, then you may diable the `self.run_epoch_eval()` in the definition [here](https://github.com/BeileiCui/EndoDAC/blob/main/trainer_end_to_end.py#L309).
